import type { TarotCard } from '@/types';

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 0,
    name: 'The Fool',
    emoji: '🃏',
    symbol: '☽',
    description: 'A new journey begins. Embrace uncertainty with open arms and a fearless heart.',
    affirmation: 'I leap boldly into the unknown, trusting the universe to catch me.',
    attribute_effects: { luck: 5, energy: 5 },
    lucky_number: 0,
    lucky_color: 'White',
    lucky_color_hex: '#F0F0F0',
    lucky_direction: 'East',
  },
  {
    id: 1,
    name: 'The Magician',
    emoji: '🔮',
    symbol: '∞',
    description: 'All tools are in your hands. Your will shapes reality itself.',
    affirmation: 'I have everything I need to manifest my desires.',
    attribute_effects: { career: 6, energy: 4, luck: 2 },
    lucky_number: 1,
    lucky_color: 'Yellow',
    lucky_color_hex: '#EAB308',
    lucky_direction: 'North',
  },
  {
    id: 2,
    name: 'The High Priestess',
    emoji: '🌙',
    symbol: '☽',
    description: 'Hidden knowledge stirs beneath the surface. Listen to your inner voice.',
    affirmation: 'I trust my intuition as my deepest guide.',
    attribute_effects: { luck: 4, love: 4, energy: 3 },
    lucky_number: 2,
    lucky_color: 'Silver',
    lucky_color_hex: '#C0C0C0',
    lucky_direction: 'West',
  },
  {
    id: 3,
    name: 'The Empress',
    emoji: '🌸',
    symbol: '♀',
    description: 'Abundance flows through you. Nature and creativity bloom under your care.',
    affirmation: 'I am a vessel of abundance, beauty, and unconditional love.',
    attribute_effects: { love: 7, wealth: 4 },
    lucky_number: 3,
    lucky_color: 'Green',
    lucky_color_hex: '#22C55E',
    lucky_direction: 'South',
  },
  {
    id: 4,
    name: 'The Emperor',
    emoji: '👑',
    symbol: '♂',
    description: 'Structure and authority build empires. Your discipline is your throne.',
    affirmation: 'I lead with strength, wisdom, and unwavering resolve.',
    attribute_effects: { career: 8, wealth: 3 },
    lucky_number: 4,
    lucky_color: 'Red',
    lucky_color_hex: '#EF4444',
    lucky_direction: 'North',
  },
  {
    id: 5,
    name: 'The Hierophant',
    emoji: '⛪',
    symbol: '☩',
    description: 'Ancient wisdom guides you. Tradition opens unexpected doors.',
    affirmation: 'I honor wisdom from the past as I build toward the future.',
    attribute_effects: { career: 5, wealth: 5 },
    lucky_number: 5,
    lucky_color: 'Red',
    lucky_color_hex: '#DC2626',
    lucky_direction: 'East',
  },
  {
    id: 6,
    name: 'The Lovers',
    emoji: '💞',
    symbol: '♡',
    description: 'Hearts align and bonds deepen. A choice made from love transforms everything.',
    affirmation: 'I choose love in every moment, for others and myself.',
    attribute_effects: { love: 8, luck: 3 },
    lucky_number: 6,
    lucky_color: 'Pink',
    lucky_color_hex: '#EC4899',
    lucky_direction: 'South',
  },
  {
    id: 7,
    name: 'The Chariot',
    emoji: '⚡',
    symbol: '⊛',
    description: 'Victory demands focused will. Charge forward — the destination is yours.',
    affirmation: 'I direct my energy with laser focus and claim my victory.',
    attribute_effects: { energy: 7, career: 4 },
    lucky_number: 7,
    lucky_color: 'Silver',
    lucky_color_hex: '#94A3B8',
    lucky_direction: 'North',
  },
  {
    id: 8,
    name: 'Strength',
    emoji: '🦁',
    symbol: '∞',
    description: 'True power is gentle mastery over your own nature. The lion yields to kindness.',
    affirmation: 'I am powerful, patient, and compassionate.',
    attribute_effects: { energy: 5, love: 4, luck: 2 },
    lucky_number: 8,
    lucky_color: 'Orange',
    lucky_color_hex: '#F97316',
    lucky_direction: 'East',
  },
  {
    id: 9,
    name: 'The Hermit',
    emoji: '🕯️',
    symbol: '△',
    description: 'Solitude reveals what crowds obscure. Your inner lantern never dims.',
    affirmation: 'I find clarity and wisdom in stillness.',
    attribute_effects: { luck: 3, energy: 6, career: 2 },
    lucky_number: 9,
    lucky_color: 'Grey',
    lucky_color_hex: '#6B7280',
    lucky_direction: 'West',
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    emoji: '🎡',
    symbol: '☸',
    description: 'The cosmic wheel turns in your favor. Fate weaves a golden thread through your life.',
    affirmation: 'I welcome every turn of fate knowing fortune favors the prepared.',
    attribute_effects: { luck: 9, wealth: 2 },
    lucky_number: 10,
    lucky_color: 'Purple',
    lucky_color_hex: '#8B5CF6',
    lucky_direction: 'All Directions',
  },
  {
    id: 11,
    name: 'Justice',
    emoji: '⚖️',
    symbol: '△',
    description: 'Balance is restored. What you have given returns to you threefold.',
    affirmation: 'I act with integrity, knowing the universe is always in balance.',
    attribute_effects: { career: 5, luck: 3, wealth: 3 },
    lucky_number: 11,
    lucky_color: 'Blue',
    lucky_color_hex: '#3B82F6',
    lucky_direction: 'East',
  },
  {
    id: 12,
    name: 'The Hanged Man',
    emoji: '🌀',
    symbol: '⊕',
    description: 'Surrender reveals sacred perspective. See the world anew from this angle.',
    affirmation: 'I release control and find liberation in surrender.',
    attribute_effects: { love: 5, energy: 3, luck: 3 },
    lucky_number: 12,
    lucky_color: 'Teal',
    lucky_color_hex: '#14B8A6',
    lucky_direction: 'West',
  },
  {
    id: 13,
    name: 'Death',
    emoji: '🌑',
    symbol: '☠',
    description: 'Transformation is total. What ends makes space for something magnificent.',
    affirmation: 'I embrace transformation as the path to my highest self.',
    attribute_effects: { energy: 6, luck: 2, career: 3 },
    lucky_number: 13,
    lucky_color: 'Black',
    lucky_color_hex: '#1F2937',
    lucky_direction: 'North',
  },
  {
    id: 14,
    name: 'Temperance',
    emoji: '🌊',
    symbol: '☆',
    description: 'Alchemy of the soul: blend all things in perfect measure. Balance is the miracle.',
    affirmation: 'I flow between worlds with grace and perfect balance.',
    attribute_effects: { love: 4, energy: 4, luck: 3 },
    lucky_number: 14,
    lucky_color: 'Lavender',
    lucky_color_hex: '#A78BFA',
    lucky_direction: 'South',
  },
  {
    id: 15,
    name: 'The Devil',
    emoji: '🔥',
    symbol: '♡',
    description: 'The chains are illusions of your own making. Break free and reclaim your fire.',
    affirmation: 'I release what binds me and step into my full, unbounded power.',
    attribute_effects: { wealth: 6, energy: 5 },
    lucky_number: 15,
    lucky_color: 'Crimson',
    lucky_color_hex: '#991B1B',
    lucky_direction: 'South',
  },
  {
    id: 16,
    name: 'The Tower',
    emoji: '⚡',
    symbol: '⊛',
    description: 'Lightning tears down falsehood. What crumbles was never truly yours to keep.',
    affirmation: 'I trust that collapse clears the path for my true foundation.',
    attribute_effects: { energy: 8, luck: 3 },
    lucky_number: 16,
    lucky_color: 'Orange-Red',
    lucky_color_hex: '#F97316',
    lucky_direction: 'All Directions',
  },
  {
    id: 17,
    name: 'The Star',
    emoji: '⭐',
    symbol: '✦',
    description: 'Hope is not naive — it is celestial. Your wish rises to meet a listening cosmos.',
    affirmation: 'I shine with hope and know that my dreams are guided by stars.',
    attribute_effects: { luck: 7, love: 4 },
    lucky_number: 17,
    lucky_color: 'Light Blue',
    lucky_color_hex: '#7DD3FC',
    lucky_direction: 'East',
  },
  {
    id: 18,
    name: 'The Moon',
    emoji: '🌕',
    symbol: '☽',
    description: 'Illusions dissolve in moonlight. Trust your instincts in the dark.',
    affirmation: 'I navigate uncertainty with trust in my deepest knowing.',
    attribute_effects: { luck: 5, love: 3, energy: 3 },
    lucky_number: 18,
    lucky_color: 'Silver-Blue',
    lucky_color_hex: '#BAE6FD',
    lucky_direction: 'West',
  },
  {
    id: 19,
    name: 'The Sun',
    emoji: '☀️',
    symbol: '☉',
    description: 'Joy radiates from your core. This is the day your light can no longer be hidden.',
    affirmation: 'I radiate joy, vitality, and the warmth of pure golden light.',
    attribute_effects: { luck: 8, energy: 5 },
    lucky_number: 19,
    lucky_color: 'Gold',
    lucky_color_hex: '#EAB308',
    lucky_direction: 'South',
  },
  {
    id: 20,
    name: 'Judgement',
    emoji: '🎺',
    symbol: '△',
    description: 'The call is clear and unmistakable. Rise — your reckoning is a resurrection.',
    affirmation: 'I answer my highest calling with courage and clarity.',
    attribute_effects: { career: 6, energy: 4, love: 3 },
    lucky_number: 20,
    lucky_color: 'Flame Orange',
    lucky_color_hex: '#EA580C',
    lucky_direction: 'North',
  },
  {
    id: 21,
    name: 'The World',
    emoji: '🌍',
    symbol: '○',
    description: 'Completion. You stand at the center of all things, whole and triumphant.',
    affirmation: 'I have arrived. I am complete. The world is mine to dance upon.',
    attribute_effects: { luck: 5, wealth: 4, love: 3, career: 3 },
    lucky_number: 21,
    lucky_color: 'Violet',
    lucky_color_hex: '#7C3AED',
    lucky_direction: 'All Directions',
  },
];

export function getRandomCard(): TarotCard {
  const index = Math.floor(Math.random() * MAJOR_ARCANA.length);
  return MAJOR_ARCANA[index];
}

export function getCardById(id: number): TarotCard | undefined {
  return MAJOR_ARCANA.find(card => card.id === id);
}
